### ISSUE TITLE
Client hangs if AWS credentials are invalid or session token does not exist

### ISSUE THREAD

**Issue by chrnorm** [common-fate/iamzero-python#2]
Thanks to @iann0036 and @highway900 for helping pick up this issue.

# Steps to reproduce
1. Create an AWS profile in `~/.aws` with invalid credentials
2. Run the [IAM Zero python example](https://github.com/common-fate/iamzero-python-example)
3. The terminal will hang with no prompt or description why

# Root cause
In `identity.py` we set up a background thread to make a single API call to AWS STS get-caller-identity when IAM Zero is initialised. To my knowledge this is the only way to reliably identity *which role* the IAM Zero client is running as. We set up an additional background thread to publish permission error batches to the IAM Zero API. This thread is blocked until `identity.py` has finished fetching the credentials to avoid dispatching permissions errors without an associated account and role IDs. However the error handling in `identity.py` needs improving: if the AWS STS get-caller-identity call fails for any reason (e.g. the credentials used are invalid) it causes the publishing thread to block indefinitely and the overall script to hang.

**Comment by highway900** [comment]
@chrnorm consider a simple context to timeout and shutdown the blocking thread if no role has been returned https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager

**Comment by chrnorm** [comment]
@highway900 I had initially implemented a [`threading.Condition`](https://docs.python.org/3/library/threading.html#condition-objects) object and have left it as is for now (#4 seems to fix the issue as per my steps to reproduce). I have added a 5 second timeout though to my `wait` call on the Condition as it is a great idea to not block the thread forever if we don't get a role.
